#!/bin/bash

# Limpiar reglas anteriores
sudo iptables -F
sudo iptables -X

# Política por defecto: bloquear todo
sudo iptables -P INPUT DROP
sudo iptables -P OUTPUT DROP
sudo iptables -P FORWARD DROP

# Permitir tráfico por loopback (localhost)
sudo iptables -A INPUT -i lo -j ACCEPT
sudo iptables -A OUTPUT -o lo -j ACCEPT

# Permitir conexiones ya establecidas
sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
sudo iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Permitir solo comunicación con el router
ROUTER_IP="192.168.1.1"


# (Opcional) Loggear lo que se bloquea
sudo iptables -N LOGDROP
sudo iptables -A LOGDROP -j LOG --log-prefix "BLOCKED LOCAL: " --log-level 4
sudo iptables -A LOGDROP -j DROP

# Aceptar tráfico desde el router
sudo iptables -A INPUT -s 192.168.1.1 -j ACCEPT
sudo iptables -A OUTPUT -d 192.168.1.1 -j ACCEPT

# Bloquear el resto de la red local
sudo iptables -A INPUT -s 192.168.1.0/24 -j DROP
sudo iptables -A OUTPUT -d 192.168.1.0/24 -j DROP


#sudo iptables -A INPUT -s 192.168.1.25 -j DROP
#sudo iptables -A OUTPUT -d 192.168.1.25 -j DROP

